# Generated by Django 6.0.5 on 2026-05-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_exchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='exchange_image',
            field=models.ImageField(blank=True, null=True, upload_to='exchange/'),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='offered_product',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
